### ISSUE TITLE
The sumo scene written by myself in VANETProject does not display

### ISSUE THREAD

**Issue by YURUI97** [chaotictoejam/VANETTutorials#1]
Thank you for your code to help me a lot.
First of all, I would like to ask if your project has been completed? Will your code be changed later?I use omnet++ 5.4.1, veins 5.0, your inet that you made modifications and sumo 0.32. There is no problem importing and running your example, and the sumo scene inside can also appear. 
Second,I want to use aodv protocol in my own vehicle motion scene. But I want to change to my own vehicle motion scene. After changing to my own vehicle motion file, it can also run, but no vehicle appears on the simulation scene interface. I am not sure what the reason is. Please help me answer this question.
[hellosumo.zip](https://github.com/chaotictoejam/VANETTutorials/files/4963531/hellosumo.zip)
![image](https://user-images.githubusercontent.com/68639368/88246171-56cea780-cccc-11ea-9df5-fe23d80258e5.png)
![image](https://user-images.githubusercontent.com/68639368/88246183-5c2bf200-cccc-11ea-9d3d-40138e08db26.png)
![image](https://user-images.githubusercontent.com/68639368/88246194-61893c80-cccc-11ea-85c5-4254969e8905.png)

**Comment by chaotictoejam** [comment]
@YURUI97 VANETProject is archived and not being worked on. You can look at this repo for tutorials on how to use OMNET++, INET, and Veins together. The [README ](https://github.com/chaotictoejam/VANETTutorials/blob/master/README.md) has links to several tutorials on YouTube. 

As for your SUMO network (hello) I do not see any issues. If you use the routing example in this repo you can see all you nodes working with your network. Please be sure to watch the tutorial for the routing example as it explains how veins_inet works.
 
You can watch the tutorial here: https://youtu.be/6GG1rPvfagU

Screenshot of your network running with AODV:
![image](https://user-images.githubusercontent.com/6563927/88289305-0c94f880-ccc3-11ea-8018-4150c9e4512e.png)
