### ISSUE TITLE
Problem in building the project

### ISSUE THREAD

**Issue by mirzayaser3** [chaotictoejam/VANETTutorials#3]
![Screenshot from 2020-12-05 15-09-06](https://user-images.githubusercontent.com/53065667/101245335-68a96800-370c-11eb-9e29-a028cb2998d3.png)
Omnetpp -5.5.1
Inet version - 3.6.8

**Comment by akshaykatyal** [comment]
Hey did you find a solution to this problem?

**Comment by adeel14553** [comment]
Did you check the compatibility?

**Comment by chaotictoejam** [comment]
Created Issue #5 to solve compatibility issues.
