### ISSUE TITLE
A runtime error occurred:

### ISSUE THREAD

**Issue by adeel14553** [chaotictoejam/VANETTutorials#4]
Unknown parameter 'router' -- in module (omnetpp::cModule) RoutingScenario.node[0] (id=10), at t=0.1s, event #2

Launch a debugger with the following command?

nemiver --attach=23827 &

I have look around Router but couldn't get rid of it.

**Comment by chaotictoejam** [comment]
INET, Veins, and Sumo have changed a lot from when this project was created. I suggest checking the versions: The README states
- INET (https://github.com/inet-framework/inet) -Latest on master as of 8/25/2020
- Veins (https://github.com/sommer/veins) -Latest on master as of 8/25/2020
- SUMO (http://sumo.sourceforge.net/) - Latest (v1.6.0)

Going above these dates/versions will most like cause issues. I'll add an issue for me to upgrade this project (as it is definitely overdue) but I am no longer actively doing research in VANETs. I promise though I will crave out time in the next few weeks.

**Comment by chaotictoejam** [comment]
Created Issue #5

**Comment by adeel14553** [comment]
Solved. It was my mistake i didn't declare routing in my ned file. Thanks a bunch.
